<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://www.mmxlabs.com/models/lng/schedule/1/"
    nsPrefix="lng.schedule">
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleModel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" lowerBound="1"
        eType="#//Schedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirty" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocations" upperBound="-1"
        eType="#//CargoAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openSlotAllocations" upperBound="-1"
        eType="#//OpenSlotAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marketAllocations" upperBound="-1"
        eType="#//MarketAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocations" upperBound="-1"
        eType="#//SlotAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fitnesses" upperBound="-1"
        eType="#//Fitness" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unusedElements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fitness" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fitnessValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargoAllocation" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject #//ProfitAndLossContainer #//EventGrouping">
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocations" lowerBound="1"
        upperBound="-1" eType="#//SlotAllocation" eOpposite="#//SlotAllocation/cargoAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputCargo" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Cargo"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarketAllocation" eSuperTypes="#//ProfitAndLossContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="market" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//SpotMarket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocation" eType="#//SlotAllocation"
        eOpposite="#//SlotAllocation/marketAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotVisit" eType="#//SlotVisit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenSlotAllocation" eSuperTypes="#//ProfitAndLossContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotAllocation" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eOperations name="getPort" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
    <eOperations name="getContract" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//Contract"/>
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spotMarket" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//SpotMarket"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocation" lowerBound="1"
        eType="#//CargoAllocation" eOpposite="#//CargoAllocation/slotAllocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marketAllocation" lowerBound="1"
        eType="#//MarketAllocation" eOpposite="#//MarketAllocation/slotAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotVisit" lowerBound="1"
        eType="#//SlotVisit" unsettable="true" eOpposite="#//SlotVisit/slotAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeTransferred" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyTransferred" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cv" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="isSpotVessel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isFleetVessel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isTimeCharterVessel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true" eOpposite="#//Event/sequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselAvailability" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//VesselAvailability"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charterInMarket" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//CharterInMarket"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fitnesses" upperBound="-1"
        eType="#//Fitness" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spotIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceType" eType="#//SequenceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//ITimezoneProvider">
    <eOperations name="getDuration" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" lowerBound="1" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousEvent" eType="#//Event"
        eOpposite="#//Event/nextEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextEvent" eType="#//Event"
        eOpposite="#//Event/previousEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" eType="#//Sequence"
        eOpposite="#//Sequence/events"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charterCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heelAtStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heelAtEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//Event #//FuelUsage #//PortVisit #//ProfitAndLossContainer #//EventGrouping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocation" lowerBound="1"
        eType="#//SlotAllocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//Event #//FuelUsage #//PortVisit #//ProfitAndLossContainer #//EventGrouping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocation" lowerBound="1"
        eType="#//SlotAllocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Journey" eSuperTypes="#//Event #//FuelUsage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laden" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toll" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Idle" eSuperTypes="#//Event #//FuelUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laden" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortVisit" eSuperTypes="#//Event #//CapacityViolationsHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portCost" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lateness" eType="#//PortVisitLateness"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotVisit" eSuperTypes="#//Event #//FuelUsage #//PortVisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slotAllocation" lowerBound="1"
        eType="#//SlotAllocation" eOpposite="#//SlotAllocation/slotVisit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselEventVisit" eSuperTypes="#//Event #//PortVisit #//ProfitAndLossContainer #//EventGrouping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselEvent" lowerBound="1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//VesselEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedCharterOut" eSuperTypes="#//PortVisit #//ProfitAndLossContainer #//EventGrouping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revenue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cooldown" eSuperTypes="#//Event #//FuelUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelUsage">
    <eOperations name="getFuelCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="int sum = 0;&#xA;for (final FuelQuantity fq : getFuels()) {&#xA;&#x9;sum += fq.getCost();&#xA;}&#xA;return sum;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuels" upperBound="-1"
        eType="#//FuelQuantity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelQuantity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuel" lowerBound="1" eType="#//Fuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="amounts" upperBound="-1"
        eType="#//FuelAmount" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelAmount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//FuelUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityViolationsHolder" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violations" upperBound="-1"
        eType="#//CapacityMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//CapacityViolationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfitAndLossContainer" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupProfitAndLoss" eType="#//GroupProfitAndLoss"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalPNLDetails" upperBound="-1"
        eType="#//GeneralPNLDetails" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupProfitAndLoss">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profitAndLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profitAndLossPreTax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityProfitAndLosses"
        upperBound="-1" eType="#//EntityProfitAndLoss" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityProfitAndLoss">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseLegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityBook" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseEntityBook"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profitAndLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profitAndLossPreTax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequenceType">
    <eLiterals name="VESSEL"/>
    <eLiterals name="SPOT_VESSEL" value="1" literal="SPOT_VESSEL"/>
    <eLiterals name="DES_PURCHASE" value="2"/>
    <eLiterals name="FOB_SALE" value="3"/>
    <eLiterals name="CARGO_SHORTS" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fuel">
    <eLiterals name="BaseFuel"/>
    <eLiterals name="FBO" value="1" literal="FBO"/>
    <eLiterals name="NBO" value="2" literal="NBO"/>
    <eLiterals name="PilotLight" value="3" literal="PilotLight"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FuelUnit">
    <eLiterals name="M3" literal="m3"/>
    <eLiterals name="MT" value="1" literal="MT"/>
    <eLiterals name="MMBTU" value="2" literal="MMBTU"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CapacityViolationType">
    <eLiterals name="MAX_LOAD"/>
    <eLiterals name="MAX_DISCHARGE" value="1"/>
    <eLiterals name="MIN_LOAD" value="2"/>
    <eLiterals name="MIN_DISCHARGE" value="3"/>
    <eLiterals name="MAX_HEEL" value="4" literal="MAX_HEEL"/>
    <eLiterals name="FORCED_COOLDOWN" value="5"/>
    <eLiterals name="VESSEL_CAPACITY" value="6" literal="VESSEL_CAPACITY"/>
    <eLiterals name="LOST_HEEL" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Calendar" instanceClassName="java.util.Calendar"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Iterable" instanceClassName="java.lang.Iterable">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPNLDetails" eSuperTypes="#//GeneralPNLDetails">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseLegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalPNLDetails" upperBound="-1"
        eType="#//GeneralPNLDetails" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotPNLDetails" eSuperTypes="#//GeneralPNLDetails">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalPNLDetails" upperBound="-1"
        eType="#//GeneralPNLDetails" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralPNLDetails" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicSlotPNLDetails" eSuperTypes="#//GeneralPNLDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraShippingPNL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalPNL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancellationFees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hedgingValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraUpsidePNL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventGrouping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" lowerBound="1"
        upperBound="-1" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortVisitLatenessType">
    <eLiterals name="PROMPT"/>
    <eLiterals name="MID_TERM" value="1"/>
    <eLiterals name="BEYOND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortVisitLateness">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PortVisitLatenessType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latenessInHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
