<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="types"
    nsURI="http://www.mmxlabs.com/models/lng/types/1/" nsPrefix="lng.types">
  <eClassifiers xsi:type="ecore:EClass" name="APort" abstract="true" eSuperTypes="#//APortSet">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.port.Port"/>
    </eAnnotations>
    <eOperations name="collect" upperBound="-1" eType="#//APort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (marked.contains(this)) {&#xA;&#x9;return org.eclipse.emf.common.util.ECollections.emptyEList();&#xA;} else {&#xA;&#x9;marked.add(this);&#xA;&#x9;return (EList&lt;APort>) org.eclipse.emf.common.util.ECollections.singletonEList((APort)this);&#xA;}&#xA;"/>
      </eAnnotations>
      <eParameters name="marked" upperBound="-1" eType="#//APortSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APortSet" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eOperations name="collect" upperBound="-1" eType="#//APort">
      <eParameters name="marked" upperBound="-1" eType="#//APortSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARoute" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.port.Route"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AVessel" abstract="true" eSuperTypes="#//AVesselSet">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.fleet.Vessel"/>
    </eAnnotations>
    <eOperations name="collect" upperBound="-1" eType="#//AVessel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (marked.contains(this)) {&#xA;&#x9;return org.eclipse.emf.common.util.ECollections.emptyEList();&#xA;} else {&#xA;&#x9;marked.add(this);&#xA;&#x9;return (EList&lt;AVessel>) org.eclipse.emf.common.util.ECollections.singletonEList((AVessel)this);&#xA;}&#xA;"/>
      </eAnnotations>
      <eParameters name="marked" upperBound="-1" eType="#//AVesselSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFleetVessel" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.fleet.Vessel"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AVesselClass" abstract="true" eSuperTypes="#//AVesselSet">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.fleet.VesselClass"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AVesselEvent" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.fleet.VesselEvent"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AContract" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.commercial.Contract"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ALegalEntity" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.commercial.LegalEntity"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AIndex" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.pricing.Index"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ACargo" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.cargo.Cargo"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASlot" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.cargo.Slot"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AVesselSet" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eOperations name="collect" upperBound="-1" eType="#//AVessel">
      <eParameters name="marked" upperBound="-1" eType="#//AVesselSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITimezoneProvider" abstract="true" interface="true">
    <eOperations name="getTimeZone" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="attribute" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABaseFuel" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.fleet.BaseFuel"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASpotMarket" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PortCapability">
    <eLiterals name="LOAD" literal="LOAD"/>
    <eLiterals name="DISCHARGE" value="1" literal="DISCHARGE"/>
    <eLiterals name="DRYDOCK" value="2" literal="DRYDOCK"/>
    <eLiterals name="MAINTENANCE" value="3" literal="MAINTENANCE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AOptimisationSettings" abstract="true"
      eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="APurchaseContract" abstract="true" eSuperTypes="#//AContract">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.commercial.PurchaseContract"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASalesContract" abstract="true" eSuperTypes="#//AContract">
    <eAnnotations source="http://www.mmxlabs.com/mmxcore/1/MMXCore">
      <details key="generatedType" value="com.mmxlabs.models.lng.commercial.SalesContract"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
