/**
 * Copyright (C) Minimax Labs Ltd., 2010 - 2022
 * All rights reserved.
 */
/* The following code was generated by JFlex 1.6.1 */

// Originally based on example from http://www2.cs.tum.edu/projekte/cup/examples.php

package com.mmxlabs.common.parser.impl;

import com.mmxlabs.common.parser.astnodes.*;

import java.time.Month;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>seriesparser.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, ParserSymbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\14\1\0\1\16\1\13\22\0\1\16\1\0\1\54"+
    "\1\6\1\0\1\62\2\0\1\56\1\57\1\60\1\4\1\55\1\12"+
    "\1\2\1\61\1\5\2\1\1\43\6\1\1\0\1\15\1\47\1\50"+
    "\1\51\1\63\1\0\1\20\1\44\1\17\1\37\1\3\1\22\1\41"+
    "\1\35\1\30\1\45\1\7\1\23\1\26\1\31\1\24\1\21\1\7"+
    "\1\25\1\34\1\36\1\42\1\40\1\7\1\32\1\46\1\7\1\52"+
    "\1\0\1\53\1\0\1\10\1\0\1\20\1\44\1\17\1\37\1\3"+
    "\1\22\1\41\1\35\1\30\1\45\1\7\1\23\1\11\1\31\1\24"+
    "\1\21\1\7\1\25\1\34\1\36\1\42\1\40\1\7\1\32\1\46"+
    "\1\7\265\0\2\27\115\0\1\33\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\4\1\2\1\1"+
    "\1\5\1\6\2\7\1\10\4\3\1\5\1\3\2\11"+
    "\4\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\3"+
    "\1\27\1\30\1\31\1\0\1\3\1\0\1\3\1\0"+
    "\7\3\3\0\3\3\1\0\6\3\1\32\1\33\2\0"+
    "\2\31\1\34\1\35\1\36\2\37\1\40\1\41\1\42"+
    "\1\43\1\3\1\44\1\45\1\46\2\0\1\46\2\3"+
    "\1\0\1\3\1\47\2\3\1\50\1\51\1\52\1\27"+
    "\1\31\1\3\2\0\2\3\2\53\2\3\1\54\1\0"+
    "\1\55\1\3\1\55\2\3\1\0\3\3\1\0\3\3"+
    "\1\0\1\3\1\56\1\0\1\3\1\0\1\3\1\0"+
    "\1\3\2\57\1\0\1\3\1\0\1\3\1\0\1\60"+
    "\1\3\1\60\1\0\1\3\1\0\1\3\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\150\0\u0138"+
    "\0\u016c\0\u01a0\0\150\0\u01d4\0\150\0\150\0\u0208\0\u023c"+
    "\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc"+
    "\0\u0410\0\u0444\0\u0478\0\150\0\u04ac\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\150\0\150\0\150\0\150\0\u04e0"+
    "\0\u0514\0\u0138\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c"+
    "\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c"+
    "\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\150\0\150\0\u0ac4"+
    "\0\u0af8\0\u0104\0\u0b2c\0\u0104\0\u0104\0\u0104\0\150\0\u0104"+
    "\0\u0104\0\u0104\0\u0104\0\u0104\0\u0b60\0\u0104\0\u0104\0\150"+
    "\0\u0b94\0\u0bc8\0\u0104\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0104"+
    "\0\u0ccc\0\u0d00\0\u0104\0\u0104\0\u0104\0\u0af8\0\150\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\150\0\u0104\0\u0e38\0\u0e6c"+
    "\0\u0104\0\u0ea0\0\150\0\u0ed4\0\u0104\0\u0f08\0\u0f3c\0\u0f70"+
    "\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110"+
    "\0\u1144\0\u0104\0\u1178\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c"+
    "\0\150\0\u0104\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u1380\0\150"+
    "\0\u13b4\0\u0104\0\u13e8\0\u141c\0\u1450\0\u1484\0\150\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\2\6"+
    "\1\12\1\13\1\14\1\15\1\16\1\15\1\17\1\20"+
    "\1\6\1\21\1\6\1\22\1\6\1\23\1\3\1\6"+
    "\1\24\1\6\1\25\1\26\1\6\1\27\1\30\1\31"+
    "\2\6\1\4\1\6\1\32\1\6\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\64\3\65\0\1\4\1\50\1\51\1\0"+
    "\1\4\1\0\3\6\5\0\10\6\1\0\3\6\1\0"+
    "\7\6\1\4\3\6\16\0\1\50\3\0\1\50\35\0"+
    "\1\50\21\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\52\1\50\1\51\1\0\1\52\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\7\6\1\52\3\6\20\0"+
    "\1\53\3\0\1\53\1\0\1\53\5\0\10\53\1\0"+
    "\3\53\1\0\7\53\1\0\3\53\16\0\1\54\1\0"+
    "\1\6\1\0\1\54\1\0\3\6\1\55\4\0\1\6"+
    "\1\56\6\6\1\57\1\60\2\6\1\0\7\6\1\54"+
    "\3\6\31\0\1\61\50\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\1\6\1\62\6\6\1\0"+
    "\3\6\1\0\13\6\16\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\2\6\1\63\5\6\1\0"+
    "\3\6\1\0\6\6\1\64\4\6\16\0\1\6\1\0"+
    "\1\65\1\0\1\6\1\0\3\6\5\0\4\6\1\66"+
    "\3\6\1\0\3\6\1\0\13\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\1\67\7\6"+
    "\1\0\3\6\1\0\13\6\16\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\1\6\1\56\6\6"+
    "\1\57\1\60\2\6\1\0\13\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\5\6\1\70"+
    "\2\6\1\0\3\6\1\0\13\6\20\0\1\71\15\0"+
    "\1\72\13\0\1\73\27\0\1\6\1\0\1\74\1\0"+
    "\1\6\1\0\3\6\5\0\2\6\1\75\5\6\1\0"+
    "\3\6\1\0\1\6\1\76\11\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\10\6\1\77"+
    "\1\100\2\6\1\0\13\6\16\0\1\6\1\0\1\101"+
    "\1\0\1\6\1\0\3\6\5\0\1\6\1\102\6\6"+
    "\1\0\3\6\1\0\13\6\16\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\5\6\1\103\2\6"+
    "\1\0\3\6\1\0\13\6\16\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\1\6\1\104\6\6"+
    "\1\0\3\6\1\0\6\6\1\105\4\6\65\0\1\106"+
    "\63\0\1\107\14\0\1\50\1\0\1\110\1\0\1\50"+
    "\35\0\1\50\21\0\1\6\1\0\1\6\1\111\1\6"+
    "\1\0\3\6\1\111\4\0\10\6\1\0\3\6\1\0"+
    "\13\6\16\0\1\53\1\0\1\53\1\0\1\53\1\0"+
    "\3\53\5\0\10\53\1\0\3\53\1\0\13\53\16\0"+
    "\1\112\1\0\1\6\1\0\1\112\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\7\6\1\112\3\6\16\0"+
    "\1\113\41\0\1\113\21\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\6\6\1\114\1\6\1\0"+
    "\2\6\1\115\1\0\12\6\1\116\46\0\1\117\33\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\0\1\6\1\120\1\6\1\0\13\6\32\0"+
    "\1\15\47\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\2\6\1\121\5\6\1\0\3\6\1\0"+
    "\13\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\6\6\1\122\1\6\1\0\3\6\1\0"+
    "\13\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\5\6\1\123"+
    "\5\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\10\6\1\124"+
    "\2\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\5\6\1\125\2\6\1\0\3\6\1\0"+
    "\13\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\2\6\1\126"+
    "\10\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\4\6\1\127"+
    "\6\6\36\0\1\130\65\0\1\131\67\0\2\132\34\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\2\6\1\133\5\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\4\6\1\134\3\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\132\1\135\2\6\1\0\13\6\20\0\1\136"+
    "\61\0\1\6\1\0\1\137\1\0\1\6\1\0\3\6"+
    "\5\0\10\6\1\0\3\6\1\0\13\6\16\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\3\6\5\0\1\140"+
    "\7\6\1\0\3\6\1\0\13\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\10\6\1\0"+
    "\3\6\1\0\2\6\1\141\10\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\4\6\1\142"+
    "\3\6\1\0\3\6\1\0\13\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\10\6\1\0"+
    "\1\6\1\143\1\6\1\0\13\6\16\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\3\6\5\0\4\6\1\144"+
    "\3\6\1\0\1\6\1\145\1\6\1\0\13\6\16\0"+
    "\1\146\2\0\1\111\1\146\4\0\1\111\30\0\1\146"+
    "\21\0\1\146\3\0\1\146\35\0\1\146\21\0\1\147"+
    "\3\0\1\147\35\0\1\147\21\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\5\6\1\150\2\6"+
    "\1\0\3\6\1\0\13\6\44\0\2\151\55\0\1\152"+
    "\42\0\1\6\1\0\1\6\1\0\1\6\1\0\3\6"+
    "\5\0\10\6\1\151\1\153\2\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\3\6\1\154\4\6\1\0\3\6\1\0\13\6\42\0"+
    "\1\155\37\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\6\6\1\156\1\6\1\0\3\6\1\0"+
    "\13\6\16\0\1\6\1\0\1\157\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\6\6\1\160\4\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\6\6\1\161\1\6\1\0\3\6\1\0\13\6\53\0"+
    "\1\162\63\0\1\163\26\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\10\6\1\0\3\6\1\0"+
    "\2\6\1\164\10\6\16\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\10\6\1\0\3\6\1\0"+
    "\2\6\1\165\10\6\16\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\5\0\10\6\1\0\3\6\1\0"+
    "\3\6\1\166\7\6\16\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\2\6\1\167\5\0\7\6\1\167\1\0"+
    "\3\6\1\0\13\6\26\0\1\170\14\0\1\170\36\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\2\6\1\171"+
    "\5\0\7\6\1\171\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\1\6\1\172\6\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\173\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\13\6\41\0\1\174\40\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\5\6\1\175\2\6\1\0\3\6\1\0\13\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\4\6\1\176\6\6\16\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\3\6\5\0"+
    "\10\6\1\0\3\6\1\0\2\6\1\177\10\6\46\0"+
    "\1\200\33\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\1\6\1\201\1\6\1\0"+
    "\13\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\0\3\6\1\0\5\6\1\202"+
    "\5\6\16\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\5\0\10\6\1\203\1\204\2\6\1\0\13\6"+
    "\53\0\1\205\26\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\3\6\5\0\10\6\1\0\3\6\1\0\2\6"+
    "\1\206\10\6\20\0\1\207\61\0\1\6\1\0\1\210"+
    "\1\0\1\6\1\0\3\6\5\0\10\6\1\0\3\6"+
    "\1\0\13\6\52\0\1\211\27\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\10\6\1\0\3\6"+
    "\1\0\1\6\1\212\11\6\42\0\1\213\37\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\3\6\5\0\6\6"+
    "\1\214\1\6\1\0\3\6\1\0\13\6\26\0\1\215"+
    "\14\0\1\215\36\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\2\6\1\216\5\0\7\6\1\216\1\0\3\6"+
    "\1\0\13\6\26\0\1\217\14\0\1\217\14\0\1\220"+
    "\21\0\1\6\1\0\1\6\1\0\1\6\1\0\2\6"+
    "\1\221\5\0\7\6\1\221\1\0\3\6\1\0\7\6"+
    "\1\222\3\6\61\0\1\223\20\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\3\6\5\0\10\6\1\0\3\6"+
    "\1\0\10\6\1\224\2\6\53\0\1\225\26\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\3\6\5\0\10\6"+
    "\1\0\3\6\1\0\2\6\1\226\10\6\57\0\1\227"+
    "\22\0\1\6\1\0\1\6\1\0\1\6\1\0\3\6"+
    "\5\0\10\6\1\0\3\6\1\0\6\6\1\230\4\6"+
    "\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5304];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\3\1\1\11\1\1\2\11"+
    "\15\1\1\11\1\1\12\11\5\1\1\0\1\1\1\0"+
    "\1\1\1\0\7\1\3\0\3\1\1\0\6\1\2\11"+
    "\2\0\5\1\1\11\10\1\1\11\2\0\3\1\1\0"+
    "\10\1\1\11\1\1\2\0\2\1\1\11\4\1\1\0"+
    "\1\11\4\1\1\0\3\1\1\0\3\1\1\0\2\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\11\2\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();
    public Lexer(java.io.Reader in, ComplexSymbolFactory sf){
	this(in);
	symbolFactory = sf;
    }
    ComplexSymbolFactory symbolFactory;

  private Symbol symbol(String name, int sym) {
      return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+yylength(),yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline+1,yycolumn+1,yychar);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    throw new com.mmxlabs.common.parser.series.GenericSeriesParsesException(message + " at column "+(yycolumn+1)+".");
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+1,yychar+1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /* throw new Error("Illegal character <"+ yytext()+">");*/
		    error("Illegal character <"+ yytext()+">");
            }
          case 50: break;
          case 2: 
            { return symbol("integer", INTEGER, Integer.valueOf(yytext()) );
            }
          case 51: break;
          case 3: 
            { return symbol("namedelement", NAMED_ELEMENT, new String(yytext()) );
            }
          case 52: break;
          case 4: 
            { return symbol("plus",PLUS  );
            }
          case 53: break;
          case 5: 
            { return symbol("m", M, Integer.valueOf(0) );
            }
          case 54: break;
          case 6: 
            { return symbol("minus",MINUS  );
            }
          case 55: break;
          case 7: 
            { /* ignore */
            }
          case 56: break;
          case 8: 
            { return symbol("semicolon",SEMICOLON);
            }
          case 57: break;
          case 9: 
            { return symbol("scurve", S);
            }
          case 58: break;
          case 10: 
            { return symbol("<",LT, ComparisonOperators.LT);
            }
          case 59: break;
          case 11: 
            { return symbol("equals",EQUALS);
            }
          case 60: break;
          case 12: 
            { return symbol(">",GT, ComparisonOperators.GT);
            }
          case 61: break;
          case 13: 
            { return symbol("[",LBRACKET);
            }
          case 62: break;
          case 14: 
            { return symbol("]",RBRACKET);
            }
          case 63: break;
          case 15: 
            { string.setLength(0); yybegin(STRING);
            }
          case 64: break;
          case 16: 
            { return symbol("comma",COMMA);
            }
          case 65: break;
          case 17: 
            { return symbol("(",LPAREN);
            }
          case 66: break;
          case 18: 
            { return symbol(")",RPAREN);
            }
          case 67: break;
          case 19: 
            { return symbol("mul",TIMES  );
            }
          case 68: break;
          case 20: 
            { return symbol("div",DIVIDE  );
            }
          case 69: break;
          case 21: 
            { return symbol("percent",PERCENT  );
            }
          case 70: break;
          case 22: 
            { return symbol("question",QUESTION  );
            }
          case 71: break;
          case 23: 
            { return symbol("float", FLOAT, new Double(yytext()) );
            }
          case 72: break;
          case 24: 
            { return symbol("var", VAR, new String(yytext()).replace("#","") );
            }
          case 73: break;
          case 25: 
            { return symbol("m", M, Integer.valueOf(yytext().replace("m","")) );
            }
          case 74: break;
          case 26: 
            { return symbol("<=",LTE, ComparisonOperators.LTE);
            }
          case 75: break;
          case 27: 
            { return symbol(">=",GTE, ComparisonOperators.GTE);
            }
          case 76: break;
          case 28: 
            { return symbol("mar",MONTH, Month.MARCH);
            }
          case 77: break;
          case 29: 
            { return symbol("max",MAX);
            }
          case 78: break;
          case 30: 
            { return symbol("may",MONTH, Month.MAY);
            }
          case 79: break;
          case 31: 
            { return symbol("min",MIN);
            }
          case 80: break;
          case 32: 
            { return symbol("cap",CAP);
            }
          case 81: break;
          case 33: 
            { return symbol("apr",MONTH, Month.APRIL);
            }
          case 82: break;
          case 34: 
            { return symbol("aug",MONTH, Month.AUGUST);
            }
          case 83: break;
          case 35: 
            { return symbol("feb",MONTH, Month.FEBRUARY);
            }
          case 84: break;
          case 36: 
            { return symbol("oct",MONTH, Month.OCTOBER);
            }
          case 85: break;
          case 37: 
            { return symbol("nov",MONTH, Month.NOVEMBER);
            }
          case 86: break;
          case 38: 
            { return symbol("sep",MONTH, Month.SEPTEMBER);
            }
          case 87: break;
          case 39: 
            { return symbol("dec",MONTH, Month.DECEMBER);
            }
          case 88: break;
          case 40: 
            { return symbol("jan",MONTH, Month.JANUARY);
            }
          case 89: break;
          case 41: 
            { return symbol("jul",MONTH, Month.JULY);
            }
          case 90: break;
          case 42: 
            { return symbol("jun",MONTH, Month.JUNE);
            }
          case 91: break;
          case 43: 
            { return symbol("tier", TIER);
            }
          case 92: break;
          case 44: 
            { return symbol("floor",FLOOR);
            }
          case 93: break;
          case 45: 
            { return symbol("shift",SHIFT);
            }
          case 94: break;
          case 46: 
            { return symbol("datedavg",DATEDAVG);
            }
          case 95: break;
          case 47: 
            { return symbol("splitmonth", SPLITMONTH);
            }
          case 96: break;
          case 48: 
            { return symbol("volumetierm3", VOLUMETIERM3);
            }
          case 97: break;
          case 49: 
            { return symbol("volumetiermmbtu", VOLUMETIERMMBTU);
            }
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
