/**
 * Copyright (C) Minimax Labs Ltd., 2010 - 2020
 * All rights reserved.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mmxlabs.common.parser.impl;

/** CUP generated interface containing symbol constants. */
public interface ParserSymbols {
  /* terminals */
  public static final int TIMES = 4;
  public static final int QUESTION = 12;
  public static final int PERCENT = 11;
  public static final int PLUS = 2;
  public static final int RPAREN = 9;
  public static final int S = 20;
  public static final int DATEDAVG = 18;
  public static final int SHIFT = 17;
  public static final int FLOOR = 14;
  public static final int LPAREN = 8;
  public static final int CAP = 13;
  public static final int COMMA = 10;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int UPLUS = 6;
  public static final int DIVIDE = 5;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int MIN = 15;
  public static final int INTEGER = 21;
  public static final int SPLITMONTH = 19;
  public static final int MAX = 16;
  public static final int NAMED_ELEMENT = 24;
  public static final int SERIES = 23;
  public static final int UMINUS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "UPLUS",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "PERCENT",
  "QUESTION",
  "CAP",
  "FLOOR",
  "MIN",
  "MAX",
  "SHIFT",
  "DATEDAVG",
  "SPLITMONTH",
  "S",
  "INTEGER",
  "NUMBER",
  "SERIES",
  "NAMED_ELEMENT"
  };
}

