/**
 * Copyright (C) Minimax Labs Ltd., 2010 - 2023
 * All rights reserved.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mmxlabs.common.parser.impl;

/** CUP generated interface containing symbol constants. */
public interface ParserSymbols {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LTE = 29;
  public static final int LBRACKET = 10;
  public static final int EQUALS = 27;
  public static final int UMINUS = 7;
  public static final int S = 23;
  public static final int MONTH = 33;
  public static final int UPLUS = 6;
  public static final int INTEGER = 34;
  public static final int CAP = 16;
  public static final int LPAREN = 8;
  public static final int M = 32;
  public static final int MINUS = 3;
  public static final int FLOOR = 17;
  public static final int PARAM = 38;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 26;
  public static final int LT = 28;
  public static final int COMMA = 12;
  public static final int PLUS = 2;
  public static final int MIN = 18;
  public static final int EOF = 0;
  public static final int RBRACKET = 11;
  public static final int error = 1;
  public static final int DATEDAVG = 21;
  public static final int PERCENT = 14;
  public static final int GTE = 31;
  public static final int TIER = 24;
  public static final int SHIFT = 20;
  public static final int TIMES = 4;
  public static final int COLON = 13;
  public static final int SERIES = 36;
  public static final int FLOAT = 35;
  public static final int NAMED_ELEMENT = 37;
  public static final int QUESTION = 15;
  public static final int MAX = 19;
  public static final int GT = 30;
  public static final int VAR = 39;
  public static final int SPLITMONTH = 22;
  public static final int TIERBLEND = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "UPLUS",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "COLON",
  "PERCENT",
  "QUESTION",
  "CAP",
  "FLOOR",
  "MIN",
  "MAX",
  "SHIFT",
  "DATEDAVG",
  "SPLITMONTH",
  "S",
  "TIER",
  "TIERBLEND",
  "SEMICOLON",
  "EQUALS",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "M",
  "MONTH",
  "INTEGER",
  "FLOAT",
  "SERIES",
  "NAMED_ELEMENT",
  "PARAM",
  "VAR"
  };
}

