<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ModelB" nsURI="http://com.mmxlabs.models.migration.tests/modelB"
    nsPrefix="ModelB">
  <eClassifiers xsi:type="ecore:EClass" name="ClassA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceA" eType="#//ClassB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
