<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mmxcore"
    nsURI="http://www.mmxlabs.com/models/mmxcore/1/" nsPrefix="models.mmxcore">
  <eClassifiers xsi:type="ecore:EClass" name="MMXObject">
    <eOperations name="makeProxies" lowerBound="1"/>
    <eOperations name="resolveProxies" lowerBound="1">
      <eParameters name="objectsByUUID" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="#//UUIDObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="restoreProxies" lowerBound="1"/>
    <eOperations name="collectUUIDObjects" lowerBound="1">
      <eParameters name="objectsByUUID" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="#//UUIDObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="collectUUIDObjects" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//UUIDObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getUnsetValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="feature" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eGetWithDefault" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="feature" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" ordered="false"
        upperBound="-1" eType="#//UUIDObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proxies" upperBound="-1"
        eType="#//MMXProxy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject" eSuperTypes="#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UUIDObject" eSuperTypes="#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMXProxy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referentID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedReferent" lowerBound="1"
        eType="#//UUIDObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referentOwner" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referentName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMXRootObject" eSuperTypes="#//UUIDObject">
    <eOperations name="addSubModel" lowerBound="1">
      <eParameters name="subModel" lowerBound="1" eType="#//UUIDObject"/>
    </eOperations>
    <eOperations name="restoreSubModels" lowerBound="1"/>
    <eOperations name="getSubModel" lowerBound="1">
      <eGenericType eTypeParameter="#//MMXRootObject/getSubModel/T"/>
      <eTypeParameters name="T"/>
      <eParameters name="subModelClass">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//MMXRootObject/getSubModel/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModels" upperBound="-1"
        eType="#//MMXSubModel" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMXSubModel" eSuperTypes="#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModelInstance" lowerBound="1"
        eType="#//UUIDObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalResource" lowerBound="1"
        eType="#//MMXResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MMXResource" instanceClassName="org.eclipse.emf.ecore.resource.Resource"/>
</ecore:EPackage>
