<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scenario"
    nsURI="http://com.mmxlabs.lng.emf" nsPrefix="com.mmxlabs.lng.emf">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fleetModel" eType="#//fleet/FleetModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portModel" eType="#//port/PortModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargoModel" eType="#//cargo/CargoModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractModel" eType="#//contract/ContractModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduleModel" eType="#//schedule/ScheduleModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marketModel" eType="#//market/MarketModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distanceModel" eType="#//port/DistanceModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalModel" eType="#//port/CanalModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimisation" eType="#//optimiser/Optimisation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eSubpackages name="fleet" nsURI="http://com.mmxlabs.lng.emf/fleet" nsPrefix="com.mmxlabs.lng.emf.fleet">
    <eClassifiers xsi:type="ecore:EClass" name="FleetModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fleet" upperBound="-1"
          eType="#//fleet/Vessel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
          eType="#//fleet/VesselClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charterOuts" upperBound="-1"
          eType="#//fleet/CharterOut" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vessel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" eType="#//fleet/VesselClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startRequirement" lowerBound="1"
          eType="#//fleet/PortAndTime" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endRequirement" lowerBound="1"
          eType="#//fleet/PortAndTime" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFuelUnitPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ladenAttributes" eType="#//fleet/VesselStateAttributes"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ballastAttributes" eType="#//fleet/VesselStateAttributes"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minHeelVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The volume of cargo below which boil-off cannot be used for fuel. Some vessels cannot access LNG below a certain level in their tanks for fuel."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.958">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ship fill capacity, as a proportion (from 0 to 1). Ship fill capacity is the percentage of vessel cargo capacity that can actually be used. Typically this is 98.5%."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dailyCharterPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cost per day of spot chartering vessels of this class, expressed in dollars"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="spotCharterCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFuelEquivalenceFactor"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.5">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The factor relating boiloff to base fuel; one unit of boiloff is equivalent to this many units of base fuel."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1"
          eType="#//port/Port">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A list of ports where this vessel can't dock because it is too large in some way."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FuelConsumptionLine">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a point on the fuel consumption curve, so a containing VesselStateAttributes will consume the associated amount of fuel at the given speed."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselStateAttributes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" eType="#//fleet/VesselState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleNBORate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleConsumptionRate"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fuelConsumptionCurve"
          upperBound="-1" eType="#//fleet/FuelConsumptionLine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VesselState">
      <eLiterals name="Laden"/>
      <eLiterals name="Ballast" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortAndTime">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//port/Port"
          unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
          unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharterOut">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
          eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
          eType="#//fleet/Vessel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
          eType="#//fleet/VesselClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="schedule" nsURI="http://com.mmxlabs.lng.emf/schedule" nsPrefix="com.mmxlabs.lng.emf.schedule">
    <eClassifiers xsi:type="ecore:EClass" name="ScheduleModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedules" upperBound="-1"
          eType="#//schedule/Schedule" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Schedule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
          eType="#//schedule/Sequence" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocations" upperBound="-1"
          eType="#//schedule/CargoAllocation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sequence">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fleetVessel" lowerBound="1"
          eType="#//fleet/Vessel" unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
          eType="#//schedule/events/ScheduledEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charterVesselClass" lowerBound="1"
          eType="#//fleet/VesselClass" unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CargoAllocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadSlot" lowerBound="1"
          eType="#//cargo/LoadSlot"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dischargeSlot" lowerBound="1"
          eType="#//cargo/Slot"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelVolume" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeVolume" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadPriceM3" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargePriceM3" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eSubpackages name="events" nsURI="http://com.mmxlabs.lng.emf/schedule/events"
        nsPrefix="com.mmxlabs.lng.emf.schedule.events">
      <eClassifiers xsi:type="ecore:EClass" name="FuelMixture">
        <eStructuralFeatures xsi:type="ecore:EReference" name="fuelUsage" upperBound="-1"
            eType="#//schedule/events/FuelQuantity" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FuelUnit">
        <eLiterals name="MT"/>
        <eLiterals name="M3" value="1"/>
        <eLiterals name="MMBTu" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FuelType">
        <eLiterals name="FBO"/>
        <eLiterals name="NBO" value="1"/>
        <eLiterals name="BaseFuel" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FuelQuantity">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelType" lowerBound="1"
            eType="#//schedule/events/FuelType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitPrice" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalPrice" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelUnit" lowerBound="1"
            eType="#//schedule/events/FuelUnit"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ScheduledEvent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Idle" eSuperTypes="#//schedule/events/PortVisit #//schedule/events/FuelMixture">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" lowerBound="1"
            eType="#//fleet/VesselState"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Journey" eSuperTypes="#//schedule/events/ScheduledEvent #//schedule/events/FuelMixture">
        <eStructuralFeatures xsi:type="ecore:EReference" name="toPort" lowerBound="1"
            eType="#//port/Port"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" lowerBound="1"
            eType="#//fleet/VesselState"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="route" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fromPort" lowerBound="1"
            eType="#//port/Port"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PortVisit" eSuperTypes="#//schedule/events/ScheduledEvent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
            eType="#//port/Port"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SlotVisit" eSuperTypes="#//schedule/events/PortVisit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1"
            eType="#//cargo/Slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocation" lowerBound="1"
            eType="#//schedule/CargoAllocation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CharterOutVisit" eSuperTypes="#//schedule/events/PortVisit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="charterOut" lowerBound="1"
            eType="#//fleet/CharterOut"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="port" nsURI="http://com.mmxlabs.lng.emf/port" nsPrefix="com.mmxlabs.lng.emf.port">
    <eClassifiers xsi:type="ecore:EClass" name="PortModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
          eType="#//port/Port" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMarket" eType="#//market/Market"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistanceModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distances" upperBound="-1"
          eType="#//port/DistanceLine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistanceLine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPort" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toPort" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Canal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classCosts" upperBound="-1"
          eType="#//port/VesselClassCost" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distanceModel" lowerBound="1"
          eType="#//port/DistanceModel" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CanalModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="canals" upperBound="-1"
          eType="#//port/Canal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselClassCost">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClass" lowerBound="1"
          eType="#//fleet/VesselClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unladenCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cargo" nsURI="http://com.mmxlabs.lng.emf/cargo" nsPrefix="com.mmxlabs.lng.emf.cargo">
    <eClassifiers xsi:type="ecore:EClass" name="CargoModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cargoes" upperBound="-1"
          eType="#//cargo/Cargo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cargo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadSlot" eType="#//cargo/LoadSlot"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dischargeSlot" eType="#//cargo/Slot"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Slot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slotDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="market" lowerBound="1"
          eType="#//market/Market" unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadSlot" eSuperTypes="#//cargo/Slot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cargoCVvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The energy content conversion factor for this cargo; because LNG is priced by MMBTU but measured by volume, we need to know both the energy content and volume. This value lets us derive the former from the latter."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="contract" nsURI="http://com.mmxlabs.lng.emf/contract" nsPrefix="com.mmxlabs.lng.emf.contract">
    <eClassifiers xsi:type="ecore:EClass" name="ContractModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseContracts" upperBound="-1"
          eType="#//contract/PurchaseContract" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="salesContracts" upperBound="-1"
          eType="#//contract/SalesContract" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="volumeConstraints" upperBound="-1"
          eType="#//contract/TotalVolumeLimit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PurchaseContract"/>
    <eClassifiers xsi:type="ecore:EClass" name="SalesContract"/>
    <eClassifiers xsi:type="ecore:EClass" name="TotalVolumeLimit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
          eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeating" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="market" nsURI="http://com.mmxlabs.lng.emf/market" nsPrefix="com.mmxlabs.lng.emf.market">
    <eClassifiers xsi:type="ecore:EClass" name="Market">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="priceCurve" lowerBound="1"
          eType="#//market/StepwisePriceCurve" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MarketModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="markets" upperBound="-1"
          eType="#//market/Market" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StepwisePriceCurve">
      <eStructuralFeatures xsi:type="ecore:EReference" name="prices" upperBound="-1"
          eType="#//market/StepwisePrice" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StepwisePrice">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceFromDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="optimiser" nsURI="http://com.mmxlabs.lng.emf/optimiser" nsPrefix="com.mmxlabs.lng.emf.optimiser">
    <eClassifiers xsi:type="ecore:EClass" name="OptimisationSettings">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//optimiser/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
          eType="#//optimiser/Objective" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Optimisation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allSettings" upperBound="-1"
          eType="#//optimiser/OptimisationSettings" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentSettings" eType="#//optimiser/OptimisationSettings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Objective">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eSubpackages name="lso" nsURI="http://com.mmxlabs.lng.emf/optimiser/lso" nsPrefix="com.mmxlabs.lng.emf.optimiser.lso">
      <eClassifiers xsi:type="ecore:EClass" name="LSOSettings" eSuperTypes="#//optimiser/OptimisationSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSteps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="thresholderSettings"
            lowerBound="1" eType="#//optimiser/lso/ThresholderSettings" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="moveGeneratorSettings"
            eType="#//optimiser/lso/MoveGeneratorSettings" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThresholderSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
            defaultValueLiteral="0.95"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialAcceptanceRate"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
            defaultValueLiteral="0.75"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="epochLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="1000"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MoveGeneratorSettings"/>
      <eClassifiers xsi:type="ecore:EClass" name="RandomMoveGeneratorSettings" eSuperTypes="#//optimiser/lso/MoveGeneratorSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using2over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using3over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using4over1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using4over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConstrainedMoveGeneratorSettings"
          eSuperTypes="#//optimiser/lso/MoveGeneratorSettings"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
