<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scenario"
    nsURI="http://com.mmxlabs.lng.emf" nsPrefix="com.mmxlabs.lng.emf">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fleetModel" eType="#//fleet/FleetModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portModel" eType="#//port/PortModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargoModel" eType="#//cargo/CargoModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractModel" eType="#//contract/ContractModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduleModel" eType="#//schedule/ScheduleModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marketModel" eType="#//market/MarketModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distanceModel" eType="#//port/DistanceModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalModel" eType="#//port/CanalModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimisation" eType="#//optimiser/Optimisation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Default name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioObject" abstract="true">
    <eOperations name="getContainer" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return eContainer();"/>
        <details key="documentation" value="This is a hack to get around the fact that EMF is not including EObject operations in getEAllOperations() for our model, probably because we are not extending the metamodel."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject" abstract="true" eSuperTypes="#//ScenarioObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="fleet" nsURI="http://com.mmxlabs.lng.emf/fleet" nsPrefix="com.mmxlabs.lng.emf.fleet">
    <eClassifiers xsi:type="ecore:EClass" name="FleetModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fleet" upperBound="-1"
          eType="#//fleet/Vessel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
          eType="#//fleet/VesselClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charterOuts" upperBound="-1"
          eType="#//fleet/CharterOut" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vessel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" eType="#//fleet/VesselClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startRequirement" lowerBound="1"
          eType="#//fleet/PortAndTime" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endRequirement" lowerBound="1"
          eType="#//fleet/PortAndTime" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeChartered" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFuelUnitPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFuelEquivalenceFactor"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.5">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The factor relating boiloff to base fuel; one unit of boiloff is equivalent to this many units of base fuel."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ladenAttributes" eType="#//fleet/VesselStateAttributes"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ballastAttributes" eType="#//fleet/VesselStateAttributes"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minHeelVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The volume of cargo below which boil-off cannot be used for fuel. Some vessels cannot access LNG below a certain level in their tanks for fuel."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.958">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ship fill capacity, as a proportion (from 0 to 1). Ship fill capacity is the percentage of vessel cargo capacity that can actually be used. Typically this is 98.5%."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dailyCharterPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cost per day of spot chartering vessels of this class, expressed in dollars"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="spotCharterCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1"
          eType="#//port/Port">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A list of ports where this vessel can't dock because it is too large in some way."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FuelConsumptionLine">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a point on the fuel consumption curve, so a containing VesselStateAttributes will consume the associated amount of fuel at the given speed."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselStateAttributes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" eType="#//fleet/VesselState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleNBORate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleConsumptionRate"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fuelConsumptionCurve"
          upperBound="-1" eType="#//fleet/FuelConsumptionLine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VesselState">
      <eLiterals name="Laden"/>
      <eLiterals name="Ballast" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortAndTime">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//port/Port"
          unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharterOut">
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
          eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
          eType="#//fleet/Vessel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
          eType="#//fleet/VesselClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="schedule" nsURI="http://com.mmxlabs.lng.emf/schedule" nsPrefix="com.mmxlabs.lng.emf.schedule">
    <eClassifiers xsi:type="ecore:EClass" name="ScheduleModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedules" upperBound="-1"
          eType="#//schedule/Schedule" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Schedule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
          eType="#//schedule/Sequence" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocations" upperBound="-1"
          eType="#//schedule/CargoAllocation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fleet" upperBound="-1"
          eType="#//schedule/fleetallocation/AllocatedVessel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fitness" upperBound="-1"
          eType="#//schedule/ScheduleFitness" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="revenue" lowerBound="1"
          upperBound="-1" eType="#//schedule/BookedRevenue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sequence">
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
          eType="#//schedule/events/ScheduledEvent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" lowerBound="1"
          eType="#//schedule/fleetallocation/AllocatedVessel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fitness" upperBound="-1"
          eType="#//schedule/ScheduleFitness" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CargoAllocation">
      <eOperations name="getTotalCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return getLadenLeg().getTotalCost() + getBallastLeg().getTotalCost()&#xA;&#x9;+ getLadenIdle().getTotalCost() + getBallastIdle().getTotalCost();"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getLocalLoadDate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getLoadSlot().getPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getLoadDate());&#xA;return calendar;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getLocalDischargeDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getDischargeSlot().getPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getDischargeDate());&#xA;return calendar;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getLoadVolume" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return getDischargeVolume() + getFuelVolume();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadSlot" lowerBound="1"
          eType="#//cargo/LoadSlot"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dischargeSlot" lowerBound="1"
          eType="#//cargo/Slot"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelVolume" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeVolume" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadPriceM3" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargePriceM3" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" lowerBound="1"
          eType="#//schedule/fleetallocation/AllocatedVessel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ladenLeg" lowerBound="1"
          eType="#//schedule/events/Journey"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ballastLeg" lowerBound="1"
          eType="#//schedule/events/Journey"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ladenIdle" lowerBound="1"
          eType="#//schedule/events/Idle"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ballastIdle" lowerBound="1"
          eType="#//schedule/events/Idle"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScheduleFitness">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LineItem" eSuperTypes="#//NamedObject">
      <eOperations name="isCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return getValue() &lt; 0;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="isRevenue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return !isCost();"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="party" lowerBound="1"
          eType="#//contract/Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BookedRevenue" eSuperTypes="#//ScenarioObject">
      <eOperations name="getUntaxedValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="int untaxedRevenue = 0;&#xA;&#xA;for (final LineItem item : getLineItems()) {&#xA;&#x9;untaxedRevenue += item.getValue();&#xA;}&#xA;&#xA;return untaxedRevenue;"/>
          <details key="documentation" value="Returns the total untaxed revenue (or if it's a net loss, a negative revenue) which the associated cargo&#xA;has produced for the associated entity.&#xA;&#xA;This is just the sum of the revenue associated with each line item."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getTaxedValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="final int untaxedRevenue = getUntaxedValue();&#xA;&#xA;if (untaxedRevenue &lt;= 0) {&#xA;&#x9;return untaxedRevenue;&#xA;} else {&#xA;&#x9;return (int) (untaxedRevenue * (1.0 - getEntity().getTaxRate()));&#xA;}"/>
          <details key="documentation" value="Returns the total revenue after tax associated with this line item."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getUntaxedRevenues" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the total revenue before tax associated with this line item."/>
          <details key="body" value="int untaxedRevenue = 0;&#xA;&#xA;for (final LineItem item : getLineItems()) {&#xA;&#x9;if (item.getValue() > 0)&#xA;&#x9;&#x9;untaxedRevenue += item.getValue();&#xA;}&#xA;&#xA;return untaxedRevenue;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getUntaxedCosts" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the total costs before tax associated with this revenue"/>
          <details key="body" value="int untaxedRevenue = 0;&#xA;&#xA;for (final LineItem item : getLineItems()) {&#xA;&#x9;if (item.getValue() &lt; 0)&#xA;&#x9;untaxedRevenue += item.getValue();&#xA;}&#xA;&#xA;return untaxedRevenue;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getTaxCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return getUntaxedValue() - getTaxedValue();"/>
          <details key="documentation" value="Returns the total amount of tax paid on this revenue"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
          eType="#//contract/Entity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cargo" lowerBound="1"
          eType="#//schedule/CargoAllocation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lineItems" upperBound="-1"
          eType="#//schedule/LineItem" containment="true"/>
    </eClassifiers>
    <eSubpackages name="events" nsURI="http://com.mmxlabs.lng.emf/schedule/events"
        nsPrefix="com.mmxlabs.lng.emf.schedule.events">
      <eClassifiers xsi:type="ecore:EClass" name="FuelMixture">
        <eOperations name="getTotalFuelCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="long totalCost = 0;&#xA;&#xA;for (final FuelQuantity quantity : getFuelUsage()) {&#xA;&#x9;totalCost += quantity.getTotalPrice();&#xA;}&#xA;&#xA;return totalCost;"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fuelUsage" upperBound="-1"
            eType="#//schedule/events/FuelQuantity" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FuelUnit">
        <eLiterals name="MT"/>
        <eLiterals name="M3" value="1"/>
        <eLiterals name="MMBTu" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FuelType">
        <eLiterals name="FBO"/>
        <eLiterals name="NBO" value="1"/>
        <eLiterals name="BaseFuel" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FuelQuantity">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelType" lowerBound="1"
            eType="#//schedule/events/FuelType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitPrice" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalPrice" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelUnit" lowerBound="1"
            eType="#//schedule/events/FuelUnit"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ScheduledEvent" eSuperTypes="#//ScenarioObject">
        <eOperations name="getEventDuration" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return (int) ((getEndTime().getTime() - getStartTime().getTime()) / javax.management.timer.Timer.ONE_HOUR); "/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getHireCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return (long) (((scenario.schedule.Sequence) eContainer()).getVessel().getHourlyCharterPrice() * getEventDuration());"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getLocalStartTime" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eOperations name="getLocalEndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Idle" eSuperTypes="#//schedule/events/PortVisit #//schedule/events/FuelMixture">
        <eOperations name="getTotalCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getTotalFuelCost() + getHireCost();"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" lowerBound="1"
            eType="#//fleet/VesselState"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Journey" eSuperTypes="#//schedule/events/ScheduledEvent #//schedule/events/FuelMixture">
        <eOperations name="getTotalCost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getRouteCost() + getTotalFuelCost() + getHireCost();"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getLocalStartTime" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getFromPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getStartTime());&#xA;return calendar;"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getLocalEndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getToPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getEndTime());&#xA;return calendar;"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toPort" lowerBound="1"
            eType="#//port/Port"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselState" lowerBound="1"
            eType="#//fleet/VesselState"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="route" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fromPort" lowerBound="1"
            eType="#//port/Port"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeCost" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PortVisit" eSuperTypes="#//schedule/events/ScheduledEvent">
        <eOperations name="getLocalStartTime" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getStartTime());&#xA;return calendar;"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getLocalEndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getEndTime());&#xA;return calendar;"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
            eType="#//port/Port"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SlotVisit" eSuperTypes="#//schedule/events/PortVisit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1"
            eType="#//cargo/Slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="cargoAllocation" lowerBound="1"
            eType="#//schedule/CargoAllocation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CharterOutVisit" eSuperTypes="#//schedule/events/PortVisit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="charterOut" lowerBound="1"
            eType="#//fleet/CharterOut"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="fleetallocation" nsURI="http://com.mmxlabs.lng.emf/schedule/fleetallocation"
        nsPrefix="com.mmxlabs.lng.emf.schedule.fleetallocation">
      <eClassifiers xsi:type="ecore:EClass" name="AllocatedVessel">
        <eOperations name="getHourlyCharterPrice" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return 0;"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FleetVessel" eSuperTypes="#//schedule/fleetallocation/AllocatedVessel">
        <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getVessel().getName();"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" lowerBound="1"
            eType="#//fleet/Vessel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SpotVessel" eSuperTypes="#//schedule/fleetallocation/AllocatedVessel">
        <eOperations name="getHourlyCharterPrice" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getVesselClass().getDailyCharterPrice() / 24.0;"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getVesselClass().getName() + &quot; &quot; + getIndex();"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClass" lowerBound="1"
            eType="#//fleet/VesselClass"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="port" nsURI="http://com.mmxlabs.lng.emf/port" nsPrefix="com.mmxlabs.lng.emf.port">
    <eClassifiers xsi:type="ecore:EClass" name="PortModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
          eType="#//port/Port" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMarket" eType="#//market/Market"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeZone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistanceModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distances" upperBound="-1"
          eType="#//port/DistanceLine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistanceLine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPort" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toPort" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Canal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classCosts" upperBound="-1"
          eType="#//port/VesselClassCost" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distanceModel" lowerBound="1"
          eType="#//port/DistanceModel" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CanalModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="canals" upperBound="-1"
          eType="#//port/Canal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VesselClassCost">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Describes the various costs and delays associated with a given vessel class for a given canal."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClass" lowerBound="1"
          eType="#//fleet/VesselClass">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The vessel class to which these costs apply, for this canal"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The toll in dollars paid for letting a laden vessel of this class pass through this canal"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unladenCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The toll in dollars for an unladen vessel of this class to pass through this canal."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="24">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The time in hours required for vessels of this class to pass through this canal"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitFuel" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="50">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The amount of base fuel or base fuel equivalent, in metric tonnes per day (MT/day), consumed by vessels of this class during their passage through the canal. The total fuel consumption for a journey through the canal is then given by transitTime * (transitFuel / 24)."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cargo" nsURI="http://com.mmxlabs.lng.emf/cargo" nsPrefix="com.mmxlabs.lng.emf.cargo">
    <eClassifiers xsi:type="ecore:EClass" name="CargoModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cargoes" upperBound="-1"
          eType="#//cargo/Cargo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cargo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadSlot" eType="#//cargo/LoadSlot"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dischargeSlot" eType="#//cargo/Slot"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allowedVessels" upperBound="-1"
          eType="#//fleet/Vessel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Slot">
      <eOperations name="getLocalWindowStart" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="final java.util.Calendar calendar = java.util.Calendar.getInstance(&#xA;java.util.TimeZone.getTimeZone(getPort().getTimeZone())&#xA;);&#xA;calendar.setTime(getWindowStart());&#xA;return calendar;"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slotDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contract" lowerBound="1"
          eType="#//contract/Contract"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadSlot" eSuperTypes="#//cargo/Slot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cargoCVvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The energy content conversion factor for this cargo; because LNG is priced by MMBTU but measured by volume, we need to know both the energy content and volume. This value lets us derive the former from the latter."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="contract" nsURI="http://com.mmxlabs.lng.emf/contract" nsPrefix="com.mmxlabs.lng.emf.contract">
    <eClassifiers xsi:type="ecore:EClass" name="ContractModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseContracts" upperBound="-1"
          eType="#//contract/PurchaseContract" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="salesContracts" upperBound="-1"
          eType="#//contract/SalesContract" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="volumeConstraints" upperBound="-1"
          eType="#//contract/TotalVolumeLimit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
          eType="#//contract/Entity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="shippingEntity" lowerBound="1"
          eType="#//contract/Entity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PurchaseContract" abstract="true"
        eSuperTypes="#//contract/Contract"/>
    <eClassifiers xsi:type="ecore:EClass" name="SalesContract" eSuperTypes="#//contract/Contract">
      <eStructuralFeatures xsi:type="ecore:EReference" name="market" lowerBound="1"
          eType="#//market/Market"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regasEfficiency" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TotalVolumeLimit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
          eType="#//port/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeating" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//NamedObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxRate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FixedPricePurchaseContract" eSuperTypes="#//contract/PurchaseContract">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitPrice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MarketPricePurchaseContract" eSuperTypes="#//contract/PurchaseContract">
      <eStructuralFeatures xsi:type="ecore:EReference" name="market" lowerBound="1"
          eType="#//market/Market"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetbackPurchaseContract" eSuperTypes="#//contract/PurchaseContract">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="buyersMargin" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProfitSharingPurchaseContract" eSuperTypes="#//contract/PurchaseContract">
      <eStructuralFeatures xsi:type="ecore:EReference" name="market" lowerBound="1"
          eType="#//market/Market"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceMarket" lowerBound="1"
          eType="#//market/Market"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="beta" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gamma" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//NamedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
          eType="#//contract/Entity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="market" nsURI="http://com.mmxlabs.lng.emf/market" nsPrefix="com.mmxlabs.lng.emf.market">
    <eClassifiers xsi:type="ecore:EClass" name="Market" eSuperTypes="#//NamedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="priceCurve" lowerBound="1"
          eType="#//market/StepwisePriceCurve" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MarketModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="markets" upperBound="-1"
          eType="#//market/Market" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StepwisePriceCurve">
      <eOperations name="getValueAtDate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return 0;"/>
        </eAnnotations>
        <eParameters name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prices" upperBound="-1"
          eType="#//market/StepwisePrice" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StepwisePrice">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceFromDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="optimiser" nsURI="http://com.mmxlabs.lng.emf/optimiser" nsPrefix="com.mmxlabs.lng.emf.optimiser">
    <eClassifiers xsi:type="ecore:EClass" name="OptimisationSettings">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//optimiser/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
          eType="#//optimiser/Objective" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialSchedule" eType="#//schedule/Schedule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Optimisation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allSettings" upperBound="-1"
          eType="#//optimiser/OptimisationSettings" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentSettings" eType="#//optimiser/OptimisationSettings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Objective">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eSubpackages name="lso" nsURI="http://com.mmxlabs.lng.emf/optimiser/lso" nsPrefix="com.mmxlabs.lng.emf.optimiser.lso">
      <eClassifiers xsi:type="ecore:EClass" name="LSOSettings" eSuperTypes="#//optimiser/OptimisationSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSteps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="thresholderSettings"
            lowerBound="1" eType="#//optimiser/lso/ThresholderSettings" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="moveGeneratorSettings"
            eType="#//optimiser/lso/MoveGeneratorSettings" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThresholderSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
            defaultValueLiteral="0.95"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialAcceptanceRate"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
            defaultValueLiteral="0.75"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="epochLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="1000"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MoveGeneratorSettings"/>
      <eClassifiers xsi:type="ecore:EClass" name="RandomMoveGeneratorSettings" eSuperTypes="#//optimiser/lso/MoveGeneratorSettings">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using2over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using3over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using4over1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="using4over2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConstrainedMoveGeneratorSettings"
          eSuperTypes="#//optimiser/lso/MoveGeneratorSettings"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
