package com.mmxlabs.models.ui.editors;

import org.eclipse.emf.common.command.Command;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.edit.domain.EditingDomain;

/**
 * Used to handle commands generated by inline editors
 * 
 * @author hinton
 *
 */
public interface ICommandHandler {
	public EditingDomain getEditingDomain();
	public void handleCommand(final Command command, final EObject target, final EStructuralFeature feature);
}
