<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="port" nsURI="http://www.mmxlabs.com/models/lng/port/1/" nsPrefix="lng.port">
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eAnnotations source="http://www.mmxlabs.com/models/mmxcore/annotations/namedobject">
      <details key="showOtherNames" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capabilities" upperBound="-1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//PortCapability"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeZone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadDuration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeDuration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="berths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cvValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="mmBtu/m³"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultStartTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowCooldown" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultWindowSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultWindowSizeUnits"
        lowerBound="1" eType="ecore:EEnum ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//TimePeriod"
        defaultValueLiteral="HOURS">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atobviacCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataloyCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesonCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UNLocode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCvValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCvValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
      <eTypeArguments eClassifier="#//Port"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//OtherNamesObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//RouteLine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeOption" eType="#//RouteOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canal" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routingOptions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryA" eType="#//EntryPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryB" eType="#//EntryPoint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortGroup">
    <eAnnotations source="http://www.mmxlabs.com/models/csv">
      <details key="namePrefix" value="Group"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
        <eTypeArguments eClassifier="#//Port"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
      <eTypeArguments eClassifier="#//Port"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteLine" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eOperations name="getFullDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vias" upperBound="-1" eType="#//RouteLine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortModel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portGroups" upperBound="-1"
        eType="#//PortGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialPortGroups" upperBound="-1"
        eType="#//CapabilityGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portCountryGroups" upperBound="-1"
        eType="#//PortCountryGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityGroup">
    <eAnnotations source="http://www.mmxlabs.com/models/csv">
      <details key="namePrefix" value="CapGroup"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capability" lowerBound="1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//PortCapability"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
      <eTypeArguments eClassifier="#//Port"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="-##0.###"/>
        <details key="exportFormatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="-##0.###"/>
        <details key="exportFormatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RouteOption">
    <eLiterals name="DIRECT"/>
    <eLiterals name="SUEZ" value="1"/>
    <eLiterals name="PANAMA" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortCountryGroup">
    <eAnnotations source="http://www.mmxlabs.com/models/csv">
      <details key="namePrefix" value="CountryGroup"/>
    </eAnnotations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
      <eTypeArguments eClassifier="#//Port"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryPoint" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
  </eClassifiers>
</ecore:EPackage>
