<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adp" nsURI="http://www.mmxlabs.com/models/lng/adp/1/" nsPrefix="lng.adp">
  <eClassifiers xsi:type="ecore:EClass" name="ADPModel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearStart" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//YearMonth"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearEnd" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//YearMonth"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseContractProfiles"
        upperBound="-1" eType="#//PurchaseContractProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="salesContractProfiles"
        upperBound="-1" eType="#//SalesContractProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fleetProfile" eType="#//FleetProfile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventoryProfiles" upperBound="-1"
        eType="#//InventoryProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FleetProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//FleetConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultNominalMarket" eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//CharterInMarket"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractProfile">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot">
        <eTypeArguments eTypeParameter="#//ContractProfile/U"/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="U">
      <eBounds eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//Contract"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract">
      <eGenericType eTypeParameter="#//ContractProfile/U"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="custom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeUnit" eType="#//LNGVolumeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProfiles" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//SubContractProfile">
        <eTypeArguments eTypeParameter="#//ContractProfile/T"/>
        <eTypeArguments eTypeParameter="#//ContractProfile/U"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ProfileConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PurchaseContractProfile">
    <eGenericSuperTypes eClassifier="#//ContractProfile">
      <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//LoadSlot"/>
      <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//PurchaseContract"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SalesContractProfile">
    <eGenericSuperTypes eClassifier="#//ContractProfile">
      <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//DischargeSlot"/>
      <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//SalesContract"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubContractProfile">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Slot">
        <eTypeArguments eTypeParameter="#//SubContractProfile/U"/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="U">
      <eBounds eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//Contract"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractType" eType="ecore:EEnum ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//ContractType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distributionModel" eType="#//DistributionModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slotTemplateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nominatedVessel" eType="ecore:EClass ../../com.mmxlabs.models.lng.fleet/model/fleet.ecore#//Vessel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shippingDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customAttribs" eType="#//CustomSubProfileAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//SubProfileConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowSizeUnits" lowerBound="1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//TimePeriod"
        defaultValueLiteral="MONTHS">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="##,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomSubProfileAttributes" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DistributionModel" abstract="true" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eOperations name="getModelOrContractVolumePerCargo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getModelOrContractVolumeUnit" eType="#//LNGVolumeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumePerCargo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeUnit" eType="#//LNGVolumeUnit"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargoSizeDistributionModel" eSuperTypes="#//DistributionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargoNumberDistributionModel" eSuperTypes="#//DistributionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfCargoes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargoByQuarterDistributionModel" eSuperTypes="#//DistributionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargoIntervalDistributionModel" eSuperTypes="#//DistributionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalType" eType="#//IntervalType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreDefinedDistributionModel" eSuperTypes="#//DistributionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" upperBound="-1"
        eType="#//PreDefinedDate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreDefinedDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntervalType">
    <eLiterals name="WEEKLY"/>
    <eLiterals name="MONTHLY" value="1"/>
    <eLiterals name="BIMONTHLY" value="2" literal="BIMONTHLY"/>
    <eLiterals name="QUARTERLY" value="3"/>
    <eLiterals name="YEARLY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowType" eSuperTypes="#//SubProfileConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyFromFlow" eSuperTypes="#//FlowType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeliverToFlow" eSuperTypes="#//FlowType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyFromProfileFlow" eSuperTypes="#//SupplyFromFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//PurchaseContractProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProfile">
      <eGenericType eClassifier="#//SubContractProfile">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//LoadSlot"/>
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//PurchaseContract"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliverToProfileFlow" eSuperTypes="#//DeliverToFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//SalesContractProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProfile">
      <eGenericType eClassifier="#//SubContractProfile">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//DischargeSlot"/>
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//SalesContract"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyFromSpotFlow" eSuperTypes="#//SupplyFromFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="market" eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//SpotMarket"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliverToSpotFlow" eSuperTypes="#//DeliverToFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="market" eType="ecore:EClass ../../com.mmxlabs.models.lng.spotmarkets/model/spotmarkets.ecore#//SpotMarket"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileVesselRestriction" eSuperTypes="#//SubProfileConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.fleet/model/fleet.ecore#//Vessel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShippingOption" eSuperTypes="#//SubProfileConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselAssignmentType" eType="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//VesselAssignmentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spotIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" eType="ecore:EClass ../../com.mmxlabs.models.lng.fleet/model/fleet.ecore#//Vessel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubProfileConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinCargoConstraint" eSuperTypes="#//ProfileConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCargoes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalType" eType="#//IntervalType"
        defaultValueLiteral="YEARLY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxCargoConstraint" eSuperTypes="#//ProfileConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCargoes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalType" eType="#//IntervalType"
        defaultValueLiteral="YEARLY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodDistributionProfileConstraint"
      eSuperTypes="#//ProfileConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distributions" upperBound="-1"
        eType="#//PeriodDistribution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodDistribution">
    <eAnnotations source="http://www.mmxlabs.com/models/featureOverride"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" upperBound="-1"
        eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//YearMonth"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCargoes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCargoes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LNGVolumeUnit">
    <eLiterals name="M3" literal="m3"/>
    <eLiterals name="MT" value="1" literal="MT"/>
    <eLiterals name="MMBTU" value="2" literal="MMBTU"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FleetConstraint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TargetCargoesOnVesselConstraint" eSuperTypes="#//FleetConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" eType="ecore:EClass ../../com.mmxlabs.models.lng.fleet/model/fleet.ecore#//Vessel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNumberOfCargoes"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalType" eType="#//IntervalType"
        defaultValueLiteral="YEARLY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InventoryProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relativeEntitlements" upperBound="-1"
        eType="#//RelativeEntitlementElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//Inventory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedSlots" upperBound="-1"
        eType="ecore:EClass ../../com.mmxlabs.models.lng.cargo/model/cargo.ecore#//LoadSlot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialAllocations" upperBound="-1"
        eType="#//AllocationElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityTable" upperBound="-1"
        eType="#//InventoryADPEntityRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeEntitlementElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseLegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entitlement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseLegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InventoryADPEntityRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../com.mmxlabs.models.lng.commercial/model/commercial.ecore#//BaseLegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialAllocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeEntitlement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
