<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fleet" nsURI="http://www.mmxlabs.com/models/lng/fleet/1/" nsPrefix="lng.fleet">
  <eClassifiers xsi:type="ecore:EClass" name="FleetModel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
        eType="#//VesselClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuels" upperBound="-1"
        eType="#//BaseFuel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselGroups" upperBound="-1"
        eType="#//VesselGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseFuel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equivalenceFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="mmBtu/mt"/>
        <details key="formatString" value="##.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vessel">
    <eOperations name="getVesselOrVesselClassCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrVesselClassFillCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getShortenedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClass" lowerBound="1"
        eType="#//VesselClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³"/>
        <details key="formatString" value="###,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1"
        unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="scale" value="100"/>
        <details key="formatString" value="###.#"/>
        <details key="unit" value="%"/>
        <details key="exportFormatString" value="#.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scnt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overrideInaccessibleRoutes"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inaccessibleRoutes" upperBound="-1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.port/model/port.ecore#//RouteOption"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
      <eTypeArguments eClassifier="#//Vessel"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuel" lowerBound="1"
        eType="#//BaseFuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³"/>
        <details key="formatString" value="###,###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="scale" value="100"/>
        <details key="formatString" value="###.#"/>
        <details key="unit" value="%"/>
        <details key="exportFormatString" value="#.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladenAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ballastAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minHeel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="###,##0"/>
        <details key="unit" value="m³"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hrs"/>
        <details key="formatString" value="##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coolingVolume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³"/>
        <details key="formatString" value="###,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeParameters" upperBound="-1"
        eType="#//VesselClassRouteParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pilotLightRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBaseFuelConsumption"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasReliqCapability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/featureEnablement">
        <details key="feature" value="reliq-support"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inaccessibleRoutes" upperBound="-1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.port/model/port.ecore#//RouteOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scnt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
      <eTypeArguments eClassifier="#//Vessel"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
      <eTypeArguments eClassifier="#//Vessel"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselStateAttributes" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inPortBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelConsumption" upperBound="-1"
        eType="#//FuelConsumption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inPortNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelConsumption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselClassRouteParameters" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTransitTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenConsumptionRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastConsumptionRate"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
