<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fleet" nsURI="http://www.mmxlabs.com/models/lng/fleet/1/" nsPrefix="lng.fleet">
  <eClassifiers xsi:type="ecore:EClass" name="FleetModel" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClasses" upperBound="-1"
        eType="#//VesselClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuels" upperBound="-1"
        eType="#//BaseFuel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselGroups" upperBound="-1"
        eType="#//VesselGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialVesselGroups" upperBound="-1"
        eType="#//VesselTypeGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioFleetModel" eType="#//ScenarioFleetModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseFuel" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//ABaseFuel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equivalenceFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VesselType">
    <eLiterals name="Owned"/>
    <eLiterals name="Time_Chartered" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vessel" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVessel">
    <eOperations name="collect" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVessel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (marked.contains(this)) return org.eclipse.emf.common.util.ECollections.emptyEList();&#xA;final org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel> result = new org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel>();&#xA;marked.add(this);&#xA;result.add(this);&#xA;return result;"/>
      </eAnnotations>
      <eParameters name="marked" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet"/>
    </eOperations>
    <eOperations name="getVesselOrVesselClassCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrVesselClassFillCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselClass" lowerBound="1"
        eType="#//VesselClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeCharterRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1"
        unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="scale" value="100"/>
        <details key="formatString" value="###.#"/>
        <details key="unit" value="%"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselClass" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselClass">
    <eOperations name="collect" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVessel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (marked.contains(this)) return org.eclipse.emf.common.util.ECollections.emptyEList();&#xA;&#x9;final org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel> result = new org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel>();&#xA;&#x9;marked.add(this);&#xA;&#x9;&#xA;&#x9;final FleetModel myModel = (FleetModel) eContainer();&#xA;&#x9;for (final Vessel v : myModel.getVessels()) {&#xA;&#x9;&#x9;if (v.getVesselClass() == this) {&#xA;&#x9;&#x9;&#x9;result.add(v);&#xA;&#x9;&#x9;}&#xA;&#x9;}&#xA;&#xA;return result;"/>
      </eAnnotations>
      <eParameters name="marked" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuel" lowerBound="1"
        eType="#//BaseFuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="scale" value="100"/>
        <details key="formatString" value="###.#"/>
        <details key="unit" value="%"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladenAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ballastAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minHeel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hrs"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coolingVolume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeParameters" upperBound="-1"
        eType="#//VesselClassRouteParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pilotLightRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/d"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselGroup" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
    <eOperations name="collect" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVessel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (marked.contains(this)) return org.eclipse.emf.common.util.ECollections.emptyEList();&#xA;final org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel> result = new org.eclipse.emf.common.util.UniqueEList&lt;com.mmxlabs.models.lng.types.AVessel>();&#xA;marked.add(this);&#xA;for (final Vessel v : getVessels()) {&#xA;&#x9;result.addAll(v.collect(marked));&#xA;}&#xA;return result;"/>
      </eAnnotations>
      <eParameters name="marked" upperBound="-1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselTypeGroup" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselType" lowerBound="1"
        eType="#//VesselType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeelOptions" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeAvailable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cvValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pricePerMMBTU" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselStateAttributes" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3/d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m3/d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inPortBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelConsumption" upperBound="-1"
        eType="#//FuelConsumption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelConsumption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselClassRouteParameters" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//ARoute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTransitTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenConsumptionRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastConsumptionRate"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioFleetModel" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselAvailabilities" upperBound="-1"
        eType="#//VesselAvailability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselEvents" upperBound="-1"
        eType="#//VesselEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselAvailability" eSuperTypes="platform:/plugin/com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startAt" upperBound="-1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAfter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startBy" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endAt" upperBound="-1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endAfter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endBy" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessel" eType="#//Vessel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startHeel" lowerBound="1"
        eType="#//HeelOptions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselEvent" abstract="true" eSuperTypes="platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselEvent platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//ITimezoneProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationInDays" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowedVessels" upperBound="-1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAfter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startBy" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceEvent" eSuperTypes="#//VesselEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DryDockEvent" eSuperTypes="#//VesselEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="CharterOutEvent" eSuperTypes="#//VesselEvent">
    <eOperations name="getEndPort" lowerBound="1" eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relocateTo" lowerBound="1"
        eType="ecore:EClass platform:/plugin/com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APort"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heelOptions" lowerBound="1"
        eType="#//HeelOptions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositioningFee" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hireRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
