<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fleet" nsURI="http://www.mmxlabs.com/models/lng/fleet/1/" nsPrefix="lng.fleet">
  <eClassifiers xsi:type="ecore:EClass" name="FleetModel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuels" upperBound="-1"
        eType="#//BaseFuel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselGroups" upperBound="-1"
        eType="#//VesselGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fleetDataVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bunkerFuelsDataVersion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vesselGroupDataVersion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fleetVersionRecord" eType="ecore:EClass ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//VersionRecord"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vesselGroupVersionRecord"
        eType="ecore:EClass ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//VersionRecord"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bunkerFuelsVersionRecord"
        eType="ecore:EClass ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//VersionRecord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseFuel" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//UUIDObject ../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equivalenceFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="mmBtu/mt"/>
        <details key="formatString" value="##.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vessel">
    <eAnnotations source="http://www.mmxlabs.com/models/featureOverride" references="#//Vessel/reference"/>
    <eOperations name="getShortenedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getVesselOrDelegateInaccessiblePorts" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getVesselOrDelegateInaccessibleRoutes" upperBound="-1" eType="ecore:EEnum ../../com.mmxlabs.models.lng.port/model/port.ecore#//RouteOption"/>
    <eOperations name="getVesselOrDelegateBaseFuel" lowerBound="1" eType="#//BaseFuel"/>
    <eOperations name="getVesselOrDelegateIdleBaseFuel" lowerBound="1" eType="#//BaseFuel"/>
    <eOperations name="getVesselOrDelegatePilotLightBaseFuel" lowerBound="1" eType="#//BaseFuel"/>
    <eOperations name="getVesselOrDelegateInPortBaseFuel" lowerBound="1" eType="#//BaseFuel"/>
    <eOperations name="getVesselOrDelegateCapacity" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrDelegateFillCapacity" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateMinSpeed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateMaxSpeed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateSafetyHeel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrDelegateWarmingTime" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrDelegateCoolingVolume" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getVesselOrDelegateRouteParameters" upperBound="-1" eType="#//VesselClassRouteParameters"/>
    <eOperations name="getVesselOrDelegatePilotLightRate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateMinBaseFuelConsumption" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateHasReliqCapability" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getVesselOrDelegateSCNT" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IMO" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Vessel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³"/>
        <details key="formatString" value="###,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="scale" value="100"/>
        <details key="formatString" value="##0.#"/>
        <details key="unit" value="%"/>
        <details key="exportFormatString" value="#.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scnt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseFuel" lowerBound="1"
        eType="#//BaseFuel" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPortBaseFuel" lowerBound="1"
        eType="#//BaseFuel" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pilotLightBaseFuel" lowerBound="1"
        eType="#//BaseFuel" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idleBaseFuel" lowerBound="1"
        eType="#//BaseFuel" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pilotLightRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.##"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safetyHeel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="formatString" value="###,##0"/>
        <details key="unit" value="m³"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coolingVolume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³"/>
        <details key="formatString" value="###,##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hrs"/>
        <details key="formatString" value="##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladenAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ballastAttributes" lowerBound="1"
        eType="#//VesselStateAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inaccessiblePortsOverride"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inaccessiblePorts" upperBound="-1">
      <eGenericType eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//APortSet">
        <eTypeArguments eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.port/model/port.ecore#//Port"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inaccessibleRoutesOverride"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inaccessibleRoutes" upperBound="-1"
        eType="ecore:EEnum ../../com.mmxlabs.models.lng.port/model/port.ecore#//RouteOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeParametersOverride"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeParameters" upperBound="-1"
        eType="#//VesselClassRouteParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBaseFuelConsumption"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasReliqCapabilityOverride"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasReliqCapability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/featureEnablement">
        <details key="feature" value="reliq-support"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mmxId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
      <eTypeArguments eClassifier="#//Vessel"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselGroup">
    <eAnnotations source="http://www.mmxlabs.com/models/csv">
      <details key="namePrefix" value="VesselGroup"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vessels" upperBound="-1"
        eType="#//Vessel"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../com.mmxlabs.models.lng.types/model/lngtypes.ecore#//AVesselSet">
      <eTypeArguments eClassifier="#//Vessel"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselStateAttributes" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eAnnotations source="http://www.mmxlabs.com/models/featureOverrideByContainer"
        references="#//Vessel/reference"/>
    <eOperations name="getVesselOrDelegateNBORate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateIdleNBORate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateIdleBaseRate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateInPortBaseRate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateServiceSpeed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateInPortNBORate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="getVesselOrDelegateFuelConsumption" lowerBound="1" upperBound="-1"
        eType="#//FuelConsumption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idleBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inPortBaseRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelConsumptionOverride"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuelConsumption" upperBound="-1"
        eType="#//FuelConsumption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inPortNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" unsettable="true">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelConsumption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="kts"/>
        <details key="formatString" value="#0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VesselClassRouteParameters" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//MMXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeOption" eType="ecore:EEnum ../../com.mmxlabs.models.lng.port/model/port.ecore#//RouteOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraTransitTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="hours"/>
        <details key="formatString" value="##0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenConsumptionRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ladenNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastConsumptionRate"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="MT/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballastNBORate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.mmxlabs.com/models/ui/numberFormat">
        <details key="unit" value="m³/day"/>
        <details key="formatString" value="##0.###"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
