<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="parameters" nsURI="http://www.mmxlabs.com/models/lng/parameters/1/"
    nsPrefix="lng.parameters">
  <eClassifiers xsi:type="ecore:EClass" name="UserSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodStart" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//YearMonth"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodEnd" eType="ecore:EDataType ../../com.mmxlabs.models.datetime/model/datetime.ecore#//YearMonth"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shippingOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateCharterOuts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildActionSets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.minimaxlabs.com/license/features/required">
        <details key="module" value="actionplan"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarityMode" eType="#//SimilarityMode"
        defaultValueLiteral="OFF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cleanStateOptimisation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatingDaysLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimilarityMode">
    <eLiterals name="ALL" literal="ALL"/>
    <eLiterals name="OFF" value="1" literal="OFF"/>
    <eLiterals name="LOW" value="2" literal="LOW"/>
    <eLiterals name="MEDIUM" value="3" literal="MEDIUM"/>
    <eLiterals name="HIGH" value="4" literal="HIGH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objective" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="../../com.mmxlabs.models.mmxcore/model/mmxcore.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnealingSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epochLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cooling" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialTemperature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restarting" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restartIterationsThreshold"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimilaritySettings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowInterval" lowerBound="1"
        eType="#//SimilarityInterval" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="medInterval" lowerBound="1"
        eType="#//SimilarityInterval" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="highInterval" lowerBound="1"
        eType="#//SimilarityInterval" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outOfBoundsWeight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimilarityInterval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptimisationPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userSettings" eType="#//UserSettings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" upperBound="-1"
        eType="#//OptimisationStage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutionBuilderSettings"
        eType="#//SolutionBuilderSettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintAndFitnessSettings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
        eType="#//Objective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatingDaysLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="15"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="similaritySettings" lowerBound="1"
        eType="#//SimilaritySettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptimisationStage" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintsAndFitnessSettingsStage"
      abstract="true" eSuperTypes="#//OptimisationStage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintAndFitnessSettings"
        eType="#//ConstraintAndFitnessSettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallisableOptimisationStage" eSuperTypes="#//OptimisationStage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelOptimisationStage" eSuperTypes="#//OptimisationStage">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//ParallisableOptimisationStage"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" containment="true">
      <eGenericType eTypeParameter="#//ParallelOptimisationStage/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleanStateOptimisationStage" eSuperTypes="#//ParallisableOptimisationStage #//ConstraintsAndFitnessSettingsStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annealingSettings" lowerBound="1"
        eType="#//AnnealingSettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSearchOptimisationStage" eSuperTypes="#//ParallisableOptimisationStage #//ConstraintsAndFitnessSettingsStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annealingSettings" lowerBound="1"
        eType="#//AnnealingSettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HillClimbOptimisationStage" eSuperTypes="#//ParallisableOptimisationStage #//ConstraintsAndFitnessSettingsStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annealingSettings" lowerBound="1"
        eType="#//AnnealingSettings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionPlanOptimisationStage" eSuperTypes="#//ConstraintsAndFitnessSettingsStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalEvaluations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inRunEvaluations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchDepth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResetInitialSequencesStage" eSuperTypes="#//OptimisationStage"/>
  <eClassifiers xsi:type="ecore:EClass" name="BreakEvenOptimisationStage" eSuperTypes="#//OptimisationStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetProfitAndLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionBuilderSettings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintAndFitnessSettings"
        eType="#//ConstraintAndFitnessSettings" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
